In [12]:
import pandas as pd
import numpy as np
from yahoo_quote_download import yqd

In [23]:

su = pd.read_csv('/Users/michaelchuang/git_project/mjc_WebScraping/webscraping/lightning2.csv')
su['bearish'] = su.bearish.apply(lambda x: x[0:].split(','))
su['bullish'] = su.bullish.apply(lambda x: x[0:].split(','))

In [24]:
#remove bearish/bullish that are the same
j2=[]
for i in range(len(su.bullish)):
    if(list((set(su.bullish[i]) - set(su.bearish[i])))==[]):
        j2.append(i)
su.drop(su.index[j2])
print()

In [25]:

##remove duplicates in bullish
for i in range(len(su.bullish)):
    su.bullish[i]=list(set(su.bullish[i]) - set(su.bearish[i]))

#remove non ticker links
for i in range(len(su.bullish)):
     su.bullish[i]= [x for x in su.bullish[i] if x.startswith('https://seekingalpha.com/symbol/')]

# remove seeking alpha

for i in range(len(su.bullish)):
    su.bullish[i] = [x.lstrip('https://seekingalpha.com/symbol/') for x in su.bullish[i]]

#same for bearish
for i in range(len(su.bearish)):
     su.bearish[i]= [x for x in su.bearish[i] if x.startswith('https://seekingalpha.com/symbol/')]

for i in range(len(su.bearish)):
      su.bearish[i]= [x.lstrip('https://seekingalpha.com/symbol/') for x in su.bearish[i]]

In [26]:

su['date'] = [x[0:10] for x in su.date]
su['date']= pd.to_datetime(su['date'])
su['enddate6m'] = su['date']+pd.DateOffset(months=6)
su['enddate30d'] = su['date']+pd.DateOffset(days=30)
su['enddate7d'] = su['date']+pd.DateOffset(days=7)
su['date']= (su['date'].astype(str))
su['enddate6m']= su['enddate6m'].astype(str)
su['enddate30d']= su['enddate30d'].astype(str)
su['enddate7d']= su['enddate7d'].astype(str)
su['date']= su['date'].str.replace('-', '')
su['enddate6m']=su['enddate6m'].str.replace('-', '')
su['enddate30d']=su['enddate30d'].str.replace('-', '')
su['enddate7d']=su['enddate7d'].str.replace('-', '')


su['yqdopen']=np.empty((len(su.date), 0)).tolist()
su['yqdclose6m']=np.empty((len(su.date), 0)).tolist()
su['yqdclose30d']=np.empty((len(su.date), 0)).tolist()
su['yqdclose7d']=np.empty((len(su.date), 0)).tolist()

In [17]:

print(su.yqdclose1m)

0       []
1       []
2       []
3       []
4       []
5       []
6       []
7       []
8       []
9       []
10      []
11      []
12      []
13      []
14      []
15      []
16      []
17      []
18      []
19      []
20      []
21      []
22      []
23      []
24      []
25      []
26      []
27      []
28      []
29      []
        ..
1129    []
1130    []
1131    []
1132    []
1133    []
1134    []
1135    []
1136    []
1137    []
1138    []
1139    []
1140    []
1141    []
1142    []
1143    []
1144    []
1145    []
1146    []
1147    []
1148    []
1149    []
1150    []
1151    []
1152    []
1153    []
1154    []
1155    []
1156    []
1157    []
1158    []
Name: yqdclose1m, Length: 1159, dtype: object

In [7]:

for i in range(len(su.bullish)):
    print('currently on row: ' + str(i))
    for j in range(len(su.bullish[i])):
        try:
            quote = (yqd.load_yahoo_quote(str(su.bullish[i][j]),su.date[i], su.enddate[i]))
            openq = quote[1].split(',')
            close7d=quote[7].split(',')
            close30d = quote[25].split(',')
            close6m= quote[-2].split(',')
        except:
            try:
                time.sleep(2)
                quote = (yqd.load_yahoo_quote(str(su.bullish[i][j]),su.date[i], su.enddate[i]))
                close7d=quote[7].split(',')
                close30d = quote[25].split(',')
                close6m= quote[-2].split(',')
            except:
                continue

        su['yqdopen'][i].append([openq[0],openq[-2]])
        su['yqdclose7d'][i].append([close7d[0],close7d[-2]])
        su['yqdclose30d'][i].append([close30d[0],close30d[-2]])
        su['yqdclose6m'][i].append([close6m[0],close6m[-2]])

currently on row: 0
[]
[]
[]
currently on row: 1
['AB', 'ULTA']
['24.457037', '255.270004']
[]
currently on row: 2
['APLE', 'FCX']
['18.053425', '14.600000']
[]
currently on row: 3
['AES', 'KMX', 'HTZ', 'VRX']
['11.040215', '66.730003', '16.650000', '17.770000']
[]
currently on row: 4
['IONS', 'XRX', 'NXPI', 'MAR', 'QCOM', 'AAPL', 'K']
['54.709999', '30.801502', '109.709999', '102.716743', '52.686417', '152.142548', '67.019653']
[]
currently on row: 5
['SNDR', 'UNP', 'ADBE']
['20.906282', '104.243263', '149.520004']
[]
currently on row: 6
['CY', 'PFE']
['14.805070', '33.215549']
[]
currently on row: 7
['CHGG', 'MCK', 'UPS', 'APO', 'SUPN']
['13.860000', '164.469269', '112.155716', '27.202108', '43.549999']
[]
currently on row: 8
['MGM', 'DATA', 'NWL', 'LYG', 'GRPN', 'CCL', 'EZU']
['32.444660', '63.759998', '53.592934', '3.506245', '3.940000', '66.359024', '41.299999']
[]
currently on row: 9
['BMO', 'INFO', 'WGO', 'SRE', 'XLNX', 'MO', 'ARNA']
['75.889427', '44.759998', '35.299999', '111.358276', '65.886726', '73.149422', '24.280001']
[]
currently on row: 10
['NVDA', 'ATNX', 'STM', 'SBUX']
['160.488708', '18.719999', '15.730661', '58.117645']
[]
currently on row: 11
['ALXN', 'INCY', 'DIS']
['124.940002', '133.220001', '104.379997']
[]
currently on row: 12
['RTN', 'GOOS']
['165.841873', '19.049999']
[]
currently on row: 13
['GD', 'PETS', 'AVAV', 'IDXX', 'NVCR', 'PTLA', 'NEE']
['200.270676', '40.341522', '39.380001', '161.509995', '18.100000', '59.630001', '140.110931']
[]
currently on row: 14
['IIVI', 'PEP', 'T']
['35.450001', '114.707298', '36.521378']
[]
currently on row: 15
['SNV', 'PH']
['44.526142', '158.782074']
[]
currently on row: 16
['NTNX', 'ULTA', 'KEY', 'RAI']
['19.750000', '289.720001', '18.022417']
[]
currently on row: 17
['ALXN', 'C', 'NYCB', 'ABBV', 'IDXX', 'AVID', 'INCY', 'MAT', 'HAS', 'ZTS']
['126.070000', '63.117702', '12.535817', '71.494118', '167.350006', '5.050000', '136.279999', '20.495577', '111.311836', '62.779999']
[]
currently on row: 18
['CARA', 'AKS', 'NUE']
['19.500000', '6.190000', '55.220001']
[]
currently on row: 19
['T', 'GOOS', 'UCTT', 'HOME']
['37.689762', '20.879999', '20.309999', '22.530001']
[]
currently on row: 20
['CMCSA', 'CMG', 'SGYP', 'BX']
['41.456860', '458.910004', '4.130000', '32.552231']
[]
currently on row: 21
['SIRI', 'XPO', 'VMW', 'CLDR', 'P']
['5.170750', '61.520000', '88.099998', '17.400000', '6.990000']
[]
currently on row: 22
['DPZ', 'INCY', 'NXPI', 'QCOM', 'HFC']
['210.046295', '120.089996', '109.269997', '56.385441', '24.928991']
[]
currently on row: 23
['ESNT', 'CARA', 'MGP', 'SCHW']
['37.169998', '17.440001', '27.972130', '41.971252']
[]
currently on row: 24
['NDAQ', 'DIS', 'SKX', 'TIF']
['69.669762', '106.249588', '27.290001', '92.110703']
[]
currently on row: 25
['GD', 'VVV', 'STZ', 'HII', 'DAR', 'TAP', 'BUD', 'ADI']
['197.841156', '23.096745', '180.514389', '192.911179', '15.860000', '86.999580', '113.500000', '78.171326']
[]
currently on row: 26
['ABT', 'ALR', 'XLNX']
['46.236702', '67.696747']
[]
currently on row: 27
['SHOP', 'SIRI']
['96.989998', '5.310500']
[]
currently on row: 28
['CRL', 'AMD', 'MU']
['93.610001', '11.240000', '31.209999']
[]
currently on row: 29
['AMAT', 'LRCX']
['45.893787', '155.583496']
[]
currently on row: 30
['SQ', 'TWTR']
['22.990000', '18.320000']
[]
currently on row: 31
['TWLO', 'BRK.B', 'BRK.A', 'DOV']
['25.010000', '82.041016']
[]
currently on row: 32
['CARA', 'NGG', 'FL']
['16.709999', '68.778046', '58.719219']
[]
currently on row: 33
['LDOS', 'CG', 'GD', 'EXC', 'SHOP', 'EBAY']
['54.274063', '17.438841', '198.347000', '35.498775', '90.809998', '34.820000']
[]
currently on row: 34
['AZN', 'SPLK', 'EXAS']
['33.564507', '66.430000', '31.900000']
[]
currently on row: 35
['SKT']
['25.634193']
[]
currently on row: 36
['WBA', 'CBSH', 'GIS', 'BDX', 'RAD']
['80.212563', '53.668770', '55.203087', '182.757462', '3.460000']
[]
currently on row: 37
['BMY', 'FUN', 'ARNC']
['54.230545', '68.305023', '27.015266']
[]
currently on row: 38
['SHOP', 'RHT', 'MO']
['85.529999', '88.610001', '69.603508']
[]
currently on row: 39
['SLB', 'AUPH', 'SWKS', 'DRI']
['70.460609', '7.260000', '100.835220', '86.122925']
[]
currently on row: 40
['ALK', 'BRKS', 'LUV']
['85.854446', '25.884750', '58.073303']
[]
currently on row: 41
['A', 'HAL']
['55.561527', '45.377567']
[]
currently on row: 42
['CCI', 'AMT', 'AWK', 'HA', 'LUV']
['92.871704', '124.708496', '78.935486', '54.299999', '55.972591']
[]
currently on row: 43
['APO', 'WING', 'MU', 'REGN', 'BX', 'NI', 'BWLD', 'SNY']
['26.232193', '29.445887', '27.629999', '366.619995', '30.485111', '24.199194', '156.399994', '45.420628']
[]
currently on row: 44
['VAC', 'S', 'BAC', 'SAGE', 'TMUS', 'ILG', 'WYN']
['109.763145', '8.910000', '23.690613', '72.160004', '67.580002', '24.095863', '99.350868']
[]
currently on row: 45
['UAL', 'ABT', 'BRK.B', 'DAL', 'AAL', 'LUV', 'JBLU', 'CARA', 'ALK']
['70.970001', '43.307320', '46.239761', '46.415699', '56.838757', '22.469999', '16.389999', '90.748222']
[]
currently on row: 46
['CXW', 'ABBV', 'BX', 'EQM', 'OCLR']
['33.092361', '63.640003', '29.120192', '75.955704', '8.910000']
[]
currently on row: 47
['GD', 'RTN', 'NOC', 'LMT', 'ABB']
['187.397156', '152.622101', '244.473495', '269.735107', '23.320000']
[]
currently on row: 48
['ZYNE', 'MDLZ']
['24.530001', '44.542778']
[]
currently on row: 49
['UBS', 'MTW', 'MOS']
['14.909003', '5.540000', '26.973270']
[]
currently on row: 50
['AMCX', 'SEMG', 'CWH', 'TSCO', 'AMN', 'SMG']
['58.090000', '33.507565', '29.015841', '62.925022', '40.099998', '92.395699']
[]
currently on row: 51
['EXC', 'VLY']
['35.526917', '11.400509']
[]
currently on row: 52
['BABA', 'COHR']
['110.440002', '199.250000']
[]
currently on row: 53
['CRBP', 'VGR', 'ALDR', 'FRT']
['7.000000', '18.963400', '19.549999', '131.835068']
[]
currently on row: 54
['TWLO', 'TGTX', 'HUBS', 'CX']
['28.170000', '10.550000', '59.599998', '8.980769']
[]
currently on row: 55
['BAC', 'GLD', 'NKTR', 'GOLD', 'VZ', 'ALKS']
['23.244370', '119.620003', '22.360001', '89.389999', '47.527607', '58.750000']
[]
currently on row: 56
['BRK.B']
[]
[]
currently on row: 57
['ORI', 'NXPI', 'AMD', 'AMGN']
['20.082136', '103.500000', '14.550000', '161.801163']
[]
currently on row: 58
['CY', 'CC', 'NBL', 'SLB', 'ZTS', 'CELG', 'AA', 'HIMX']
['13.749184', '38.109581', '34.074791', '76.676270', '53.273811', '124.339996', '33.490002', '8.470000']
[]
currently on row: 59
['RTN', 'XON', 'ARNC']
['149.746185', '20.230000', '26.079609']
[]
currently on row: 60
['STLD', 'GOOS', 'MASI', 'SMG', 'NUE']
['34.207615', '16.350000', '93.540001', '92.029839', '59.030251']
[]
currently on row: 61
['KTOS', 'SIRI', 'MAR']
['7.990000', '5.080482', '92.564995']
[]
currently on row: 62
['RRD', 'STZ', 'CIM', 'PM', 'MO', 'CY']
['11.419675', '163.143219', '18.590120', '109.790688', '71.811737', '14.116180']
[]
currently on row: 63
['FLEX', 'HSY']
['16.639999', '106.853127']
[]
currently on row: 64
['DAL', 'TELL', 'VOYA', 'STM', 'CUDA']
['46.358501', '11.360000', '39.228363', '15.310259', '23.309999']
[]
currently on row: 65
['NOV', 'GOV', 'GE', 'WFC']
['39.195049', '19.372192', '29.336920', '57.841068']
[]
currently on row: 66
['AOBC', 'KLAC', 'AMAT', 'LRCX']
['19.549999', '93.067963', '38.872734', '125.280312']
[]
currently on row: 67
['CSCO', 'SYY', 'CYBR', 'CHKP']
['33.341988', '51.586895', '50.000000', '100.730003']
[]
currently on row: 68
['ABT', 'ABBV', 'SONC', 'SWKS']
['44.067024', '63.997372', '23.319645', '98.210701']
[]
currently on row: 69
['BURL', 'ROST', 'TJX']
['93.769997', '66.600647', '77.404457']
[]
currently on row: 70
['CWH', 'MRVL', 'ANET', 'AAOI']
['31.318514', '16.162199', '124.169998', '50.919998']
[]
currently on row: 71
['ICE', 'MU']
['59.495159', '25.150000']
[]
currently on row: 72
['MMP', 'TGTX', 'ARNC', 'THS', 'KMI']
['74.664902', '10.150000', '26.726622', '85.139999', '21.032734']
[]
currently on row: 73
['ROP', 'T']
['210.777328', '40.346989']
[]
currently on row: 74
['AMD']
['13.040000']
[]
currently on row: 75
['NDSN', 'GSK', 'ASX']
['124.452843', '40.988609', '5.908052']
[]
currently on row: 76
['KBR', 'TTC']
['14.780700', '59.893696']
[]
currently on row: 77
['NTAP', 'PENN']
['42.403606', '14.630000']
[]
currently on row: 78

['PYPL', 'CHRW', 'TXN']
['42.000000', '78.886246', '75.686348']
[]
currently on row: 79
['PANW', 'CSCO', 'ED', 'SKT']
['153.949997', '33.361462', '75.178413', '33.865570']
[]
currently on row: 80
['BOX', 'VZ', 'TMUS']
['17.930000', '48.770973', '62.209999']
[]
currently on row: 81
['HCA', 'MU', 'WDC', 'AMD', 'FCX', 'INCY', 'MET', 'SWKS']
['86.449997', '23.480000', '73.308044', '14.320000', '13.480000', '121.949997', '46.942146', '94.751106']
[]
currently on row: 82
['MMP', 'MU', 'MOS', 'PFG', 'AGCO', 'SHLX', 'POT']
['78.246864', '23.350000', '32.826473', '60.773029', '63.723202', '32.333996', '18.401548']
[]
currently on row: 83
['NVDA', 'HSY', 'INO', 'CQP', 'ACN']
['106.907997', '105.802124', '7.000000', '31.228373', '118.334320']
[]
currently on row: 84
['ENB', 'AQN', 'CBG', 'AKS', 'NUE']
['41.799633', '8.735647', '35.439999', '8.490000', '62.618534']
[]
currently on row: 85
['PCLN', 'ZLTQ', 'SLB', 'CHK']
['1637.290039', '81.227203', '6.440000']
[]
currently on row: 86
['BMY', 'X', 'OLED']
['50.988163', '39.533493', '64.745316']
[]
currently on row: 87
['SAIC', 'ACC', 'SHOP', 'REVG', 'THO']
['82.336212', '48.319687', '55.220001', '27.899645', '108.379868']
[]
currently on row: 88
['PNRA', 'MIC', 'PLAY', 'BLK']
['75.411751', '56.790001', '371.646942']
[]
currently on row: 89
['SAN', 'MB', 'AMGN', 'BCS', 'NYCB', 'FI']
['5.186863', '25.150000', '164.659515', '11.115607', '14.322523', '12.075022']
[]
currently on row: 90
['BOX', 'EXEL', 'AAL']
['17.730000', '20.570000', '44.881878']
[]
currently on row: 91
['MEI', 'KTOS', 'CRZO']
['41.138210', '8.850000', '34.470001']
[]
currently on row: 92
['TWI', 'D', 'XLNX']
['12.901230', '69.679253', '57.260551']
[]
currently on row: 93
['SN', 'ACM']
['13.180000', '36.549999']
[]
currently on row: 94
['RCL', 'TECK', 'CCL']
['92.565735', '25.205757', '54.445755']
[]
currently on row: 95
['AGU', 'MOS', 'WY', 'AGCO', 'CSCO', 'POT']
['100.176994', '30.656937', '30.467043', '62.402920', '29.914303', '18.283592']
[]
currently on row: 96
['GLOP', 'AGN']
['20.874405', '209.983749']
[]
currently on row: 97
['PI', 'COHR', 'MTW']
['35.400002', '156.690002', '7.500000']
[]
currently on row: 98
['XLNX']
['57.949013']
[]
currently on row: 99
['TTWO', 'ATVI']
['52.160000', '38.295536']
[]
currently on row: 100
['JPM', 'BAC', 'C', 'WFC', 'PNC']
['82.256065', '22.382818', '55.543655', '53.925686', '115.463470']
[]
currently on row: 101
['IDT', 'BBT', 'HOG', 'EPD']
['18.290430', '44.380943', '57.017834', '26.475752']
[]
currently on row: 102
['MPC', 'HUN', 'HD']
['47.848278', '19.797794', '133.767731']
[]
currently on row: 103
['NXPI']
['97.620003']
[]
currently on row: 104
['AMT', 'HAS', 'MAT']
['101.918335', '82.429031', '28.344015']
[]
currently on row: 105
['MDR', 'BRK.B', 'FCX', 'WEC', 'SAP', 'MTD', 'ACN']
['7.420000', '15.270000', '57.211674', '88.239227', '421.920013', '113.491936']
[]
currently on row: 106
['CWH']
['31.762400']
[]
currently on row: 107
['MMP', 'HRL', 'GWPH', 'STAG', 'EQT']
['71.231178', '34.398033', '123.809998', '22.864286', '63.246006']
[]
currently on row: 108
['TWLO', 'WDC', 'ADNT', 'T']
['70.624969', '55.252968', '39.306522']
[]
currently on row: 109
['VOD', 'ASIX', 'ECA', 'ARNC']
['25.252359', '22.320000', '12.891718', '20.481138']
[]
currently on row: 110
['AMD', 'MRK', 'KMB', 'COST', 'SON']
['11.240000', '58.818287', '113.391655', '155.212601', '52.534378']
[]
currently on row: 111
['CG', 'SIRI', 'MDT', 'TXMD', 'AAPL']
['15.482500', '4.503163', '70.108246', '6.420000', '114.594292']
[]
currently on row: 112
['AGN', 'BLUE', 'GSK', 'ASH', 'SWN']
['197.307632', '64.650002', '36.917454', '53.095787', '11.010000']
[]
currently on row: 113
['EOG', 'MAT', 'WR']
['102.420311', '27.211023', '54.980499']
[]
currently on row: 114
['JCI']
['42.036091']
[]
currently on row: 115
['VMI', 'HD', 'MAS']
['150.196976', '134.701019', '32.094051']
[]
currently on row: 116
['BOBE', 'ABM', 'FNSR', 'MOMO', 'HA', 'BMY', 'ALK']
['47.784225', '39.403858', '31.170000', '18.080000', '57.349998', '57.069355', '87.805473']
[]
currently on row: 117
['KKR', 'OPK']
['16.208960', '11.900000']
[]
currently on row: 118
[]
[]
[]
currently on row: 119
[]
[]
[]
currently on row: 120
[]
[]
[]
currently on row: 121
[]
[]
[]
currently on row: 122
[]
[]
[]
currently on row: 123
['P', 'EW']
['13.780000', '83.220001']
[]
currently on row: 124
[]
[]
[]
currently on row: 125
[]
[]
[]
currently on row: 126
['BLK', 'CHK', 'HAL']
['359.628693', '6.370000', '47.062035']
[]
currently on row: 127
['WOR', 'APC', 'NUE', 'DVN']
['60.735069', '64.755844', '60.910755', '44.754158']
[]
currently on row: 128
['GKOS', 'AEP', 'WEN', 'CVX']
['32.720001', '57.638012', '12.457808', '107.388840']
[]
currently on row: 129
['ABT', 'DY', 'HHC']
['38.858475', '92.949997', '108.629997']
[]
currently on row: 130
['MUR', 'AMAT', 'STM']
['29.891588', '30.416142', '9.264503']
[]
currently on row: 131
['BAC', 'ULTA', 'CHD', 'MS', 'NWL']
['19.778522', '251.130005', '43.922062', '39.399303', '46.754044']
[]
currently on row: 132
['BWLD', 'TEP', 'ZOES']
['164.100006', '44.174416', '22.840000']
[]
currently on row: 133
['AMT', 'TECD', 'DNKN', 'ARW', 'EPD', 'KR']
['101.403008', '80.690002', '49.086861', '65.690002', '24.485527']
[]
currently on row: 134
['SYF', 'ARIA', 'GE', 'SUPN']
['33.279518', '29.496449', '23.900000']
[]
currently on row: 135
['TMUS']
['52.540001']
[]
currently on row: 136
['BRK.B']
[]
[]
currently on row: 137
['OLLI', 'WMT', 'SIX', 'GILD', 'FDX', 'CY']
['28.100000', '69.178459', '54.392811', '76.278137', '179.577484']
[]
currently on row: 138
['HDP']
[]
[]
currently on row: 139
['TECD', 'WDC']
['77.769997', '56.274979']
[]
currently on row: 140
['AIG', 'UVE', 'HRL', 'VOD', 'ALL', 'EW']
['56.223450', '19.126911', '35.885464', '25.593351', '65.558739', '89.629997']
[]
currently on row: 141
[]
[]
[]
currently on row: 142
['CR', 'WM', 'TSEM']
['65.901878', '62.186192', '15.440000']
[]
currently on row: 143
['RPM', 'HPQ', 'ATVI', 'CELG', 'NTNX']
['46.060699', '13.917997', '42.340767', '104.089996', '24.160000']
[]
currently on row: 144
['ANIK', 'BX', 'BSX', 'GILD', 'JNPR']
['44.360001', '23.194279', '22.000000', '71.573326', '25.964012']
[]
currently on row: 145
[]
[]
[]
currently on row: 146
['KBH', 'OI', 'PFE']
['14.131478', '19.459999', '31.224739']
[]
currently on row: 147
['YUM', 'STZ', 'MNST', 'SMG']
['60.812752', '164.724625', '48.700001', '86.674255']
[]
currently on row: 148
['IDXX', 'MGM', 'AA', 'DIS']
['110.980003', '25.796869', '21.166847', '91.361015']
[]
currently on row: 149
[]
[]
[]
currently on row: 150
['VSAT', 'ASIX', 'VVC']
['72.980003', '16.370001', '47.098392']
[]
currently on row: 151
['ICE', 'TECD', 'PFE', 'CVS', 'CLVS', 'CHTR']
['52.758736', '80.150002', '31.340101', '84.363663', '32.599998', '260.200012']
[]
currently on row: 152
['SYF', 'PG', 'V', 'RDUS']
['26.171740', '84.778275', '80.979683', '52.520000']
[]
currently on row: 153
['CERN', 'ORI', 'STM', 'AMD']
['60.830002', '17.651976', '7.976127', '6.670000']
[]
currently on row: 154
['KMI', 'ARIA', 'RDUS', 'OPK']
['19.882401', '52.529999', '9.450000']
[]
currently on row: 155
['BABA']
['103.620003']
[]
currently on row: 156
['RYAM', 'MXL']
['13.135655', '21.389999']
[]
currently on row: 157
['GOLD', 'HIG', 'ED', 'T']
['87.250229', '42.813725', '69.492874', '37.016945']
[]
currently on row: 158
['GLOG', 'MGM', 'HON']
['14.592861', '26.509054', '113.191231']
[]
currently on row: 159
['KR', 'CVS', 'AWK']
['28.364243', '84.168365', '69.700165']
[]
currently on row: 160
['FLEX', 'HD', 'BRKS', 'ETN']
['13.570000', '125.575523', '13.293882', '63.696285']
[]
currently on row: 161
['CECE', 'WM']
['10.953491', '62.303444']
[]
currently on row: 162
['AIR', 'ATRA', 'SXC']
['29.734983', '20.660000', '7.600000']
[]
currently on row: 163
['DNKN', 'IFF', 'BERY', 'AMAT', 'IP']
['49.135700', '138.529709', '45.680000', '29.327730', '45.781796']
[]
currently on row: 164
['PI', 'AMD', 'EPD', 'BLUE']
['32.130001', '6.320000', '25.558365', '71.269997']
[]
currently on row: 165
['TWLO', 'CLVS', 'AVGO', 'WY']
['64.919998', '38.360001', '165.736160', '30.885925']
[]
currently on row: 166
['CMI', 'MU', 'NVDA', 'INTC', 'KR', 'SWKS', 'AA']
['117.619888', '17.660000', '64.556519', '36.359653', '30.331247', '75.772652', '23.146082']
[]
currently on row: 167

['CLX', 'NRG', 'TSCO', 'AKS', 'K']
['120.310432', '11.342870', '66.460205', '4.300000', '75.043823']
[]
currently on row: 168
['CLCD', 'BRK.B', 'NXPI']
['82.989998']
[]
currently on row: 169
['MMP', 'EPD', 'KMI', 'ON', 'XRX', 'NXPI', 'SWKS', 'AA']
['64.712112', '24.512280', '20.966362', '25.202326', '83.750000', '75.111099', '22.595556']
[]
currently on row: 170
['ELLI', 'TSS']
['92.320000', '47.031082']
[]
currently on row: 171
['VGR', 'ABBV', 'AMD', 'IP']
['17.961039', '60.551823', '5.740000', '46.003475']
[]
currently on row: 172
['DVAX', 'CY', 'BLK']
['12.190000', '11.340238', '359.189606']
[]
currently on row: 173
['F', 'CLF']
['11.723148', '5.610000']
[]
currently on row: 174
['CMI', 'TECD', 'AVID', 'DIS', 'IBM', 'CAT']
['116.608261', '71.519997', '8.160000', '92.680946', '153.203278', '80.867287']
[]
currently on row: 175
['GE']
['29.795635']
[]
currently on row: 176
['ELLI', 'ECA', 'OXY', 'MGA', 'JCP', 'MO']
['98.800003', '9.720346', '73.186943', '40.100391', '9.490000', '63.919910']
[]
currently on row: 177
['YELP', 'NVCR', 'AGU', 'POT']
['38.889999', '7.750000', '92.394157', '17.305544']
[]
currently on row: 178
['NVAX', 'APD']
['6.840000', '139.424408']
[]
currently on row: 179
['ANTM', 'CI', 'OPK']
['122.834679', '128.186218', '9.330000']
[]
currently on row: 180
['CYBR', 'CXO', 'CRZO', 'OXY']
['132.839996', '38.000000']
[]
currently on row: 181
['MU', 'NVDA', 'GE', 'FIVE', 'NXPI', 'EW', 'VEEV', 'AVGO']
['16.200001', '61.242104', '29.939528', '47.080002', '87.610001', '114.769997', '38.869999', '172.284210']
[]
currently on row: 182
['BOX', 'AKRX']
['13.070000', '27.940001']
[]
currently on row: 183
['XPO']
['37.220001']
[]
currently on row: 184
['ABBV', 'CPHD']
['63.190331']
[]
currently on row: 185
[]
[]
[]
currently on row: 186
['AWK', 'GWPH']
['80.500885', '94.320000']
[]
currently on row: 187
[]
[]
[]
currently on row: 188
['FTR', 'CAT', 'MTW']
['72.418793', '81.409378', '5.690000']
[]
currently on row: 189
['LVS', 'AMGN', 'IT', 'GILD', 'CELG', 'WYNN', 'MXL']
['47.641834', '162.174149', '100.129997', '78.311699', '106.180000', '101.013390', '22.360001']
[]
currently on row: 190
['VAC', 'BC', 'LNCE']
['75.043839', '48.387955', '34.678898']
[]
currently on row: 191
['DLR']
['97.747154']
[]
currently on row: 192
[]
[]
[]
currently on row: 193
['CBRL', 'DHR', 'SFL']
['145.444077', '80.225487', '12.350489']
[]
currently on row: 194
['VOD', 'JCI', 'TYC']
['28.924639', '39.041386']
[]
currently on row: 195
['CRUS', 'BX', 'RDUS', 'KMI', 'CCC']
['40.470001', '22.927221', '39.000000', '20.283745', '13.699575']
[]

In [11]:
print(su['yqdopen']-su['yqdclose'])

ValueError: operands could not be broadcast together with shapes (0,) (196,)

In [23]:
yqd.load_yahoo_quote(str(su.bullish[i][j]),su.date[i], su.enddate[i])[-2].split(',')[-2]

'16.564627'

['Date,Open,High,Low,Close,Adj Close,Volume',
 '2017-08-03,112.239998,119.500000,112.080002,118.440002,118.130859,8252300',
 '2017-08-04,119.900002,121.730003,118.260002,119.000000,118.689392,5455700',
 '2017-08-07,127.180000,128.429993,122.309998,127.070000,126.738327,13683600',
 '2017-08-08,124.239998,126.330002,123.889999,125.699997,125.371902,3672100',
 '2017-08-09,125.559998,128.149994,125.330002,126.430000,126.099998,4227300',
 '2017-08-10,125.410004,126.419998,125.070000,125.750000,125.750000,2371700',
 '2017-08-11,125.930000,126.690002,124.209999,124.580002,124.580002,2253500',
 '2017-08-14,125.169998,126.980003,124.599998,125.739998,125.739998,1447600',
 '2017-08-15,125.779999,126.300003,124.389999,124.830002,124.830002,1881500',
 '2017-08-16,124.930000,125.629997,124.589996,125.449997,125.449997,1327000',
 '2017-08-17,125.150002,125.230003,122.849998,122.889999,122.889999,1242900',
 '2017-08-18,122.750000,124.839996,121.459999,124.519997,124.519997,2708800',
 '2017-08-21,124.459999,124.650002,123.040001,123.690002,123.690002,1877000',
 '2017-08-22,124.370003,124.750000,123.599998,124.290001,124.290001,1013900',
 '2017-08-23,124.650002,125.239998,124.019997,124.589996,124.589996,1395700',
 '2017-08-24,127.370003,130.369995,126.570000,129.279999,129.279999,4259800',
 '2017-08-25,129.449997,130.350006,128.139999,129.089996,129.089996,2329400',
 '2017-08-28,129.199997,129.440002,127.160004,127.989998,127.989998,2006800',
 '2017-08-29,127.580002,135.309998,127.309998,130.740005,130.740005,5738300',
 '2017-08-30,131.220001,131.630005,129.940002,130.539993,130.539993,2524100',
 '2017-08-31,130.789993,131.279999,130.320007,131.050003,131.050003,1573700',
 '2017-09-01,130.899994,131.169998,130.509995,130.610001,130.610001,1532400',
 '2017-09-05,132.070007,132.210007,130.910004,131.000000,131.000000,16983000',
 '2017-09-06,131.000000,131.029999,130.500000,130.550003,130.550003,5720700',
 '2017-09-07,130.600006,131.899994,130.539993,131.350006,131.350006,5647100',
 '2017-09-08,131.130005,131.339996,130.759995,130.949997,130.949997,2786100',
 '2017-09-11,131.009995,131.240005,130.589996,130.809998,130.809998,3018500',
 '2017-09-12,130.839996,131.289993,130.759995,130.970001,130.970001,1505400',
 '2017-09-13,130.899994,131.360001,130.839996,131.210007,131.210007,2100800',
 '2017-09-14,131.100006,131.520004,131.000000,131.350006,131.350006,2816600',
 '2017-09-15,131.509995,131.550003,130.899994,131.089996,131.089996,2931900',
 '2017-09-18,131.100006,131.240005,130.449997,130.559998,130.559998,5027600',
 '2017-09-19,130.490005,131.009995,130.210007,130.570007,130.570007,3654600',
 '2017-09-20,130.690002,130.800003,129.929993,130.149994,130.149994,5215800',
 '2017-09-21,130.100006,130.880005,129.970001,130.389999,130.389999,2097900',
 '2017-09-22,130.419998,130.679993,129.990005,130.479996,130.479996,1980400',
 '2017-09-25,130.289993,130.649994,130.009995,130.009995,130.009995,3647900',
 '2017-09-26,129.860001,130.449997,129.729996,129.910004,129.910004,3423900',
 '2017-09-27,129.979996,130.770004,129.860001,130.220001,130.220001,1793400',
 '2017-09-28,130.199997,130.490005,129.960007,130.110001,130.110001,2445000',
 '2017-09-29,130.029999,130.710007,129.699997,130.710007,130.710007,1933500',
 '2017-10-02,130.720001,131.589996,130.559998,131.460007,131.460007,1958100',
 '2017-10-03,131.500000,132.470001,131.240005,132.220001,132.220001,1838700',
 '2017-10-04,132.259995,133.160004,132.259995,133.160004,133.160004,1535400',
 '2017-10-05,133.160004,133.250000,132.490005,132.899994,132.899994,1527700',
 '2017-10-06,132.979996,133.220001,132.110001,132.619995,132.619995,1042800',
 '2017-10-09,132.729996,133.300003,132.729996,133.199997,133.199997,1324500',
 '2017-10-10,133.220001,134.050003,132.789993,133.960007,133.960007,1383600',
 '2017-10-11,134.149994,134.679993,134.009995,134.600006,134.600006,1768400',
 '2017-10-12,134.520004,135.119995,134.509995,134.940002,134.940002,1377500',
 '2017-10-13,134.979996,135.149994,134.509995,134.710007,134.710007,1052800',
 '2017-10-16,134.800003,135.119995,134.449997,134.679993,134.679993,862700',
 '2017-10-17,134.520004,134.789993,134.320007,134.529999,134.529999,767400',
 '2017-10-18,134.649994,134.770004,134.190002,134.610001,134.610001,1466600',
 '2017-10-19,134.470001,134.960007,134.199997,134.570007,134.570007,1043293',
 '']

In [26]:
print((yqd.load_yahoo_quote(str(su.bullish[170][0]),su.date[170], su.enddate[170])[0]).split(',')[-2])

16.564627

In [37]:
su.bullish[170]

['CRUS', 'BX', 'RDUS', 'KMI', 'CCC']

In [28]:
len(su.bearish)

196

In [19]:
quote=yqd.load_yahoo_quote(str(su.bullish[1][0]),su.date[1], su.enddate1m[1])
quote

['Date,Open,High,Low,Close,Adj Close,Volume',
 '2017-08-01,24.750000,25.000000,24.600000,24.950001,24.457037,265100',
 '2017-08-02,24.850000,24.950001,24.600000,24.799999,24.309999,267500',
 '2017-08-03,24.100000,24.549999,24.049999,24.299999,24.299999,341600',
 '2017-08-04,24.299999,24.450001,24.180000,24.299999,24.299999,215300',
 '2017-08-07,24.200001,24.750000,24.150000,24.650000,24.650000,324800',
 '2017-08-08,24.650000,24.850000,24.559999,24.700001,24.700001,298800',
 '2017-08-09,24.500000,24.799999,24.350000,24.400000,24.400000,214300',
 '2017-08-10,24.450001,24.450001,23.400000,23.799999,23.799999,433000',
 '2017-08-11,23.500000,24.000000,23.150000,23.750000,23.750000,253100',
 '2017-08-14,23.900000,24.250000,23.750000,24.000000,24.000000,194100',
 '2017-08-15,24.000000,24.080000,23.799999,23.850000,23.850000,202100',
 '2017-08-16,23.799999,23.950001,23.549999,23.600000,23.600000,158900',
 '2017-08-17,23.450001,23.549999,23.100000,23.150000,23.150000,149400',
 '2017-08-18,23.000000,23.350000,22.549999,23.100000,23.100000,256600',
 '2017-08-21,23.049999,23.730000,23.049999,23.350000,23.350000,285900',
 '2017-08-22,23.200001,23.700001,23.200001,23.600000,23.600000,242400',
 '2017-08-23,23.250000,23.750000,23.250000,23.549999,23.549999,226200',
 '2017-08-24,23.650000,23.650000,23.250000,23.250000,23.250000,149400',
 '2017-08-25,23.299999,23.750000,23.250000,23.350000,23.350000,184400',
 '2017-08-28,23.350000,23.500000,23.200001,23.299999,23.299999,153200',
 '2017-08-29,23.000000,23.400000,23.000000,23.200001,23.200001,157700',
 '2017-08-30,23.100000,23.400000,22.900000,23.250000,23.250000,124700',
 '2017-08-31,23.250000,23.600000,23.250000,23.450001,23.450001,149100',
 '2017-09-01,23.350000,23.750000,23.299999,23.600000,23.600000,174200',
 '']

In [32]:
quote[25]

''

In [28]:
su.enddate30d[1]

'20170831'

In [35]:
su.date

0       20170803
1       20170801
2       20170728
3       20170726
4       20170725
5       20170721
6       20170719
7       20170718
8       20170714
9       20170713
10      20170712
11      20170711
12      20170710
13      20170707
14      20170706
15      20170626
16      20170623
17      20170621
18      20170620
19      20170619
20      20170616
21      20170614
22      20170613
23      20170612
24      20170609
25      20170608
26      20170607
27      20170605
28      20170601
29      20170531
          ...
1129    20110128
1130    20110126
1131    20110125
1132    20110124
1133    20110121
1134    20110120
1135    20110119
1136    20110117
1137    20110114
1138    20110113
1139    20110111
1140    20110110
1141    20110106
1142    20110105
1143    20110104
1144    20101224
1145    20101223
1146    20101222
1147    20101221
1148    20101219
1149    20101217
1150    20101216
1151    20101215
1152    20101213
1153    20101210
1154    20101209
1155    20101208
1156    20101207
1157    20101206
1158    20101203
Name: date, Length: 1159, dtype: object

In [34]:
quote

['Date,Open,High,Low,Close,Adj Close,Volume',
 '2017-08-01,253.139999,257.059998,252.449997,255.270004,255.270004,1117800',
 '2017-08-02,255.000000,255.350006,246.100006,247.970001,247.970001,1187800',
 '2017-08-03,246.940002,251.979996,246.240005,251.279999,251.279999,676400',
 '2017-08-04,252.149994,254.589996,250.009995,250.199997,250.199997,460900',
 '2017-08-07,249.559998,251.919998,248.529999,248.809998,248.809998,617700',
 '2017-08-08,248.889999,252.869995,247.229996,250.639999,250.639999,537100',
 '2017-08-09,249.850006,254.419998,249.179993,253.080002,253.080002,668600',
 '2017-08-10,252.089996,252.199997,246.690002,246.869995,246.869995,685400',
 '2017-08-11,247.949997,251.979996,247.949997,251.050003,251.050003,385700',
 '2017-08-14,251.800003,252.880005,247.449997,248.470001,248.470001,680600',
 '2017-08-15,248.809998,248.929993,237.360001,237.669998,237.669998,1574700',
 '2017-08-16,238.020004,245.100006,236.000000,243.429993,243.429993,1302200',
 '2017-08-17,241.830002,245.250000,240.960007,241.429993,241.429993,678500',
 '2017-08-18,240.850006,247.360001,240.850006,244.199997,244.199997,813400',
 '2017-08-21,236.669998,240.000000,233.020004,234.210007,234.210007,1804700',
 '2017-08-22,236.369995,239.979996,231.160004,231.649994,231.649994,2165700',
 '2017-08-23,231.000000,233.440002,228.500000,232.059998,232.059998,2861100',
 '2017-08-24,240.000000,247.300003,233.020004,233.710007,233.710007,2884700',
 '2017-08-25,215.440002,217.800003,208.250000,212.360001,212.360001,7890200',
 '2017-08-28,210.199997,211.380005,207.000000,207.750000,207.750000,2745200',
 '2017-08-29,205.139999,212.729996,204.009995,211.779999,211.779999,1754200',
 '2017-08-30,211.380005,213.880005,210.589996,213.570007,213.570007,1511200',
 '2017-08-31,214.820007,221.149994,214.470001,221.009995,221.009995,2070900',
 '2017-09-01,221.119995,222.270004,218.759995,221.729996,221.729996,1646300',
 '2017-09-05,221.000000,223.940002,220.009995,223.899994,223.899994,1622500',
 '2017-09-06,224.289993,228.089996,223.770004,228.000000,228.000000,1519000',
 '2017-09-07,228.520004,231.279999,228.250000,230.529999,230.529999,1626400',
 '2017-09-08,229.660004,229.660004,226.000000,226.979996,226.979996,1112500',
 '2017-09-11,227.869995,228.889999,227.119995,228.600006,228.600006,716000',
 '2017-09-12,229.539993,229.559998,225.520004,226.880005,226.880005,1006400',
 '2017-09-13,225.979996,227.690002,225.710007,226.410004,226.410004,716600',
 '2017-09-14,225.339996,226.029999,221.690002,223.929993,223.929993,1439400',
 '2017-09-15,223.490005,224.880005,222.809998,224.669998,224.669998,937600',
 '2017-09-18,225.729996,228.690002,225.339996,227.080002,227.080002,1061100',
 '2017-09-19,227.380005,227.550003,222.630005,224.449997,224.449997,802900',
 '2017-09-20,223.889999,226.919998,221.880005,223.839996,223.839996,622600',
 '2017-09-21,224.720001,224.720001,219.699997,219.740005,219.740005,847900',
 '2017-09-22,219.009995,221.690002,218.360001,219.169998,219.169998,767700',
 '2017-09-25,219.639999,220.630005,218.130005,218.889999,218.889999,904600',
 '2017-09-26,219.000000,220.759995,218.669998,218.990005,218.990005,1422200',
 '2017-09-27,219.279999,228.800003,219.279999,227.660004,227.660004,1168700',
 '2017-09-28,227.440002,228.589996,226.029999,226.889999,226.889999,549700',
 '2017-09-29,226.300003,227.910004,224.619995,226.059998,226.059998,562100',
 '2017-10-02,226.929993,226.990005,218.330002,223.800003,223.800003,1063600',
 '2017-10-03,222.470001,227.789993,221.759995,227.619995,227.619995,893200',
 '2017-10-04,226.759995,227.419998,222.850006,223.520004,223.520004,600200',
 '2017-10-05,223.529999,224.990005,220.619995,220.630005,220.630005,1229600',
 '2017-10-06,219.419998,221.330002,219.100006,219.910004,219.910004,1479200',
 '2017-10-09,220.100006,220.899994,215.610001,217.339996,217.339996,631100',
 '2017-10-10,217.149994,217.839996,212.690002,212.690002,212.690002,835300',
 '2017-10-11,212.190002,212.679993,207.669998,207.889999,207.889999,2061100',
 '2017-10-12,201.520004,201.779999,189.500000,190.160004,190.160004,5496000',
 '2017-10-13,191.979996,200.899994,187.960007,198.580002,198.580002,3790600',
 '2017-10-16,196.119995,197.399994,192.110001,193.699997,193.699997,2309800',
 '2017-10-17,196.440002,202.660004,195.270004,202.279999,202.279999,1994000',
 '2017-10-18,197.809998,201.160004,196.610001,198.369995,198.369995,2400300',
 '2017-10-19,198.059998,208.690002,197.119995,204.619995,204.619995,2701100',
 '2017-10-20,205.720001,207.550003,203.169998,204.850006,204.850006,693445',
 '']

In [33]:
openq = quote[6].split(',')
openq

['2017-08-08',
 '248.889999',
 '252.869995',
 '247.229996',
 '250.639999',
 '250.639999',
 '537100']

In [20]:
[openq[0],openq[-2]]

['2017-08-08', '250.639999']